### ISSUE TITLE
Deploy script end abrupty

### ISSUE THREAD

**Issue by ksprashu** [apigee/openbank#14]
Could give a link on where to start
Some sample postman scripts
etc.

**Comment by kidiyoor** [comment]
I think the new deploy script [edge-launchpad](https://github.com/apigee/edge-launchpad) addresses part of this issue. Although Edge-launchpad is not true idempotent, the deploy script can be re-run if there is abrupty and it will clean the previous 'abrupt partial setup' and bring up new setup.

can we close this issue ?

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
