### ISSUE TITLE
setup script: send debug / trace info to a log file

### ISSUE THREAD

**Issue by ksprashu** [apigee/openbank#16]
don't throw so much log info during setup
just tell what is happening (steps)
write rest to a log file

**Comment by kidiyoor** [comment]
New deploy script using - [edge-launchpad](https://github.com/apigee/edge-launchpad), displays limited log. Edge-Launchpad doesn't write logs to a file. It makes sense to have logging ability for edge-launchpad. 
Creating an issue for edge-launchpad for the same - [issue13](https://github.com/apigee/edge-launchpad/issues/13)
