### ISSUE TITLE
Debit / Credit transaction type

### ISSUE THREAD

**Issue by ksprashu** [apigee/openbank#43]
There should be a field in the payment transaction that indicates if the transaction is a debit / credit type. However currently the API that makes a transaction entry is the payment API which will make only a debit transaction - so the use case needs to be discussed further.

Reference : https://community.apigee.com/questions/39727/open-banking-identify-the-transaction-is-a-debit-o.html?childToView=39875#comment-39875

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
