### ISSUE TITLE
can not retrieve nodejs log 

### ISSUE THREAD

**Issue by YasuhideKato** [apigee/openbank#45]
I tried to get  consent-app nodejs log with apigeetool, however I could not retrieve logs.
I checked and changed a following codes, it is available.

```
app.js
// development error handler
// will print stacktrace
//if (app.get('env') === 'development') {
if (app.get('env') === 'test') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}
```

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
