### ISSUE TITLE
Add tests for Payment APIs

### ISSUE THREAD

**Issue by seantdg** [apigee/openbank#58]
The BDD test coverage for Account APIs is excellent. It would be great to also do this for Payment APIs.

**Comment by rohan-m** [comment]
@seantdg 
Please look forward for this in the beta release, there are slight modifications for the entire test scripts.

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
