### ISSUE TITLE
Add a 404 Resource not found.

### ISSUE THREAD

**Issue by seantdg** [apigee/openbank#59]
If a conditional flow is not found in the Proxy Endpoint, we should return a 404 instead of a TargetEndpoint not found error.

**Comment by seantdg** [comment]
Pull request for this change here: https://github.com/apigee/openbank/pull/69

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
