### ISSUE TITLE
Add configurable traffic management to all proxies.

### ISSUE THREAD

**Issue by seantdg** [apigee/openbank#60]
In order to protect the APIs from traffic spikes, we should add Spike Arrests to the PreFlow of each API Proxy.

We can have a KVM called 'TrafficLimits' where...
Key = API Proxy name
Value = Spike Arrest Rate.

This way, customers can configure the spike arrest just by changing the KVM value. By default we can set the values to 9999tps.

**Comment by rohan-m** [comment]
@seantdg 
It will be a good add on to include polices like spike arrest.
But using KVM for configuration will be a costly operation.

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
