### ISSUE TITLE
Offer static mocks as an alternative to BaaS

### ISSUE THREAD

**Issue by seantdg** [apigee/openbank#61]
Some customers may not have access to a BaaS instance. We can create static mocks for these customers.

**Comment by seantdg** [comment]
We can use something like this: https://community.apigee.com/articles/27779/how-to-mock-a-target-backend-with-a-nodejs-api-pro-1.html

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
