### ISSUE TITLE
Unit testing for complex JavaScript extensions

### ISSUE THREAD

**Issue by seantdg** [apigee/openbank#62]
There are a few complex javascript callouts, e.g. https://github.com/apigee/openbank/blob/master/src/gateway/oauth/apiproxy/resources/jsc/ValidateRequestJWT.js

We should unit test these as shown in https://community.apigee.com/articles/3964/unit-testing-javascript-code-with-mocha-sinon-and.html

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
