### ISSUE TITLE
Use consistent error handling and Add DefaultFaultRule to catch unhandling errors.

### ISSUE THREAD

**Issue by seantdg** [apigee/openbank#65]
In many places, we aren't catching unhandled errors. We can follow these steps: https://community.apigee.com/articles/23724/an-error-handling-pattern-for-apigee-proxies.html

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
