### ISSUE TITLE
Logging capability

### ISSUE THREAD

**Issue by seantdg** [apigee/openbank#67]
We could either give an example or write in the README how to do add Logging to this solution.

A good code example is here: https://github.com/seymen/accelerator-ci-maven/blob/master/currency-v1/apiproxy/resources/jsc/LogToLoggly.js

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
