### ISSUE TITLE
I can retrieve accounts with an access token whose scope is "openid payments"

### ISSUE THREAD

**Issue by booyildirim** [apigee/openbank#71]
I retrieve an access token using oauth app with the type of "code id_token" with payments scope

The payload is:
{
  "ClientId": "t2GAyc1RM9tAr4PBeswlD1NG6pi00ILH",
  "ResponseType": "code id_token",
  "ResponseTypeToken": "true",
  "ResponseTypeCode": "false",
  "ResponseTypeIdToken": "false",
  "Scope": "openid payments",
  "RedirectUri": "http://localhost/",
  "RequestId": "1001",
  "RequestState": "af0ifjsldkj",
  "ApplicationName": "AISP_App_v2",
  "CustomerId": "10203040",
  "Nonce": "n-0S6_WzA2Mj",
  "TppId": "12345"
}

After that, I used the responded access token within Authorization header with Bearer and could get /accounts response with that token.

**Comment by rohan-m** [comment]
Hi @booyildirim ,

This payload is used internally and there is no validation as of now on this payload.

This call is made with internal key and thus these payloads are not meant to be modified(internal keys not shared to the app developer)
