### ISSUE TITLE
Redirect Url of Mobile App not working for OpenBank 

### ISSUE THREAD

**Issue by satishashokbhor** [apigee/openbank#72]
Hi Team,
If provided redirect url as mobile app "deep link" url then after popup getting error on redirect url "deep link" i.e. <scheme>://
But It seems to be working perfect for urls starting with http or https

Is it supported by open bank to give proper status back to Mobile App redirect url.

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
