### ISSUE TITLE
gulpify should do npm install in the proxies

### ISSUE THREAD

**Issue by ksprashu** [apigee/openbank#8]
@mukundha FYI

**Comment by mukundha** [comment]
ok now we are doing the following in seed - would npm install go into gulp?
```
npm install
gulp deploy
```

**Comment by kidiyoor** [comment]
[Edge-Launchpad](https://github.com/apigee/edge-launchpad) fixes this issue. Default behaviour of Edge-Launchpad is to do NPM install inside proxies that have node resource.
