### ISSUE TITLE
Username entered twice when launching logging page with Chrome in MacOS

### ISSUE THREAD

**Issue by apichick** [apigee/openbank#84]
When running the "gulp test" command some of the tests open a chrome browser and when entering the username to log in the username string appears duplicated, and the test fails.

![screen shot 2018-05-31 at 1 26 59 pm](https://user-images.githubusercontent.com/19226769/40782138-5787b6ea-64d6-11e8-86c7-9530888ec8fb.png)

**Comment by apichick** [comment]
The problem is caused by the fact that the login form is prepolated with credentials

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
