### ISSUE TITLE
Templated files are not written correctly if the path to the template file has a dot in it

### ISSUE THREAD

**Issue by jorisvddonk** [apigee/openbank#91]
If your path to the openbank repository contains at least one dot (`.`), templated files (like `config.yml` and `test/testbank_jwt.pem`) are not written correctly, causing all kinds of issues when deploying to apigee.

For example, on my system, `/Users/joris.van-de-donk/openbank/config.yml.template` gets processed and saved as `/Users/joris.van-de-donk/openbank/config`.

This is caused by https://github.com/apigee/openbank/blob/5a649d2b74dc1b9ec05fb0a931dca4928b5dc211/gulpfile.js#L211, which doesn't take dots in the path into account.

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
