### ISSUE TITLE
Error deploying proxy oauth

### ISSUE THREAD

**Issue by herediasamuel** [apigee/openbank#94]
Hi! After executing the command 
and follow the steps : gulp openbankdeploy --env test, 
I get this error

`[23:37:36] error deploying proxy oauth
[23:37:36] Error: Error uploading policy Generate-Id-Token.xml: {
  "code" : "rest.SchemaValidationFailure",
  "message" : "Schema validation failed. Cause : unexpected element (uri:\"\", local:\"Value\"). Expected elements are <{\u0000}text>. Line number : 22. Column number : 9. File name : NA.",
  "contexts" : [ ]
}`

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
